import { motion } from 'framer-motion'
import { Leaf, Sun, BatteryCharging, Zap, ShieldCheck } from 'lucide-react'

export default function SustainabilitySection() {
  const lifecycleSteps = [
    {
      step: '01',
      title: 'Solar & Wind Generation',
      desc: '100% renewable electricity generated by solar panels and local wind farms.',
      icon: Sun,
      image: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?fm=jpg&q=60&w=3000&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y2FyfGVufDB8fDB8fHww',
    },
    {
      step: '02',
      title: 'BESS Battery Storage',
      desc: 'Utility-scale battery storage balances grid power during peak demand hours.',
      icon: BatteryCharging,
      image: 'https://i.pinimg.com/236x/cb/3f/aa/cb3faad4081700bc23512e3da79a3073.jpg',
    },
    {
      step: '03',
      title: 'Ultra-Fast 350kW Dispenser',
      desc: 'Liquid-cooled cables pump up to 350 miles of range per hour, redefining your EV.',
      icon: Zap,
      image: 'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?auto=format&fit=crop&w=800&q=85',
    },
    {
      step: '04',
      title: 'Zero-Emission Driving',
      desc: 'Replace fossil fuels and minimize carbon emissions completely.',
      icon: Leaf,
      image: 'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=800&q=85',
    },
  ]

  return (
    <section className="relative py-8 sm:py-12 bg-[#F0F7ED] overflow-hidden">
      {/* Background glow accent */}
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[600px] h-[350px] bg-[#059669]/10 rounded-full blur-[140px] pointer-events-none" />

      <div className="relative z-10 max-w-[1440px] mx-auto px-4 sm:px-8 lg:px-12 space-y-6">
        
        {/* ── Top Hero Section (Compact & Centred) ── */}
        <div className="text-center max-w-2xl mx-auto space-y-2.5">
          <motion.div
            initial={{ opacity: 0, y: 12 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-[#E8F8C8] text-[#059669] text-[11px] font-extrabold uppercase tracking-wider border border-[#059669]/20 shadow-sm"
          >
            <ShieldCheck className="h-3.5 w-3.5" /> 100% Renewable Energy Guarantee
          </motion.div>

          <motion.h2
            initial={{ opacity: 0, y: 14 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.1 }}
            className="text-2xl sm:text-3xl lg:text-5xl font-black text-slate-900 tracking-tight leading-tight"
          >
            Powered by Sun &amp; Wind.{' '}
            <span className="relative inline-block text-[#059669]">
              Zero Grid Strain.
              <motion.span
                initial={{ scaleX: 0 }}
                whileInView={{ scaleX: 1 }}
                viewport={{ once: true }}
                transition={{ duration: 0.8, delay: 0.4, ease: [0.16, 1, 0.3, 1] }}
                style={{ originX: 0 }}
                className="absolute -bottom-0.5 left-0 right-0 h-[3px] rounded-full bg-[#00D66C]"
              />
            </span>
          </motion.h2>

          <motion.p
            initial={{ opacity: 0, y: 12 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.2 }}
            className="text-slate-600 text-xs sm:text-sm font-medium leading-relaxed max-w-lg mx-auto"
          >
            Clean, reliable, and future-ready energy solutions for a greener, stronger <span className="font-extrabold text-[#059669]">India</span>.
          </motion.p>
        </div>

       

        {/* ── 4 Lifecycle Step Cards with FULL BG IMAGE BANNERS ── */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5 sm:gap-6">
          {lifecycleSteps.map((item, idx) => {
            const Icon = item.icon
            return (
              <motion.div
                key={item.step}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: idx * 0.1, duration: 0.5 }}
                className="group relative rounded-3xl overflow-hidden bg-slate-900 border border-slate-800 shadow-xl hover:shadow-2xl hover:border-[#00D66C]/60 transition-all duration-500 h-[400px] sm:h-[480px] lg:h-[500px] flex flex-col justify-between p-6 sm:p-8 cursor-pointer"
              >
                {/* FULL CARD BACKGROUND IMAGE */}
                <img
                  src={item.image}
                  alt={item.title}
                  className="absolute inset-0 w-full h-full object-cover group-hover:scale-108 transition-transform duration-700 brightness-90"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-slate-950 via-slate-950/65 to-slate-950/10" />
                <div className="absolute inset-0 bg-gradient-to-b from-slate-950/10 via-transparent to-slate-950/50" />

                {/* Top Row: Step badge left, Icon right */}
                <div className="relative z-10 flex items-center justify-between">
                  <span className="px-3 py-1 rounded-full bg-slate-950/80 border border-slate-700 text-[#00D66C] text-xs font-black backdrop-blur-md">
                    {item.step}
                  </span>
                  <div className="h-10 w-10 rounded-2xl bg-[#00D66C]/20 border border-[#00D66C]/40 text-[#00D66C] flex items-center justify-center backdrop-blur-md">
                    <Icon className="h-5 w-5" />
                  </div>
                </div>

                {/* Bottom Content Row */}
                <div className="relative z-10 space-y-3">
                  <h3 className="text-xl font-black text-white leading-snug">{item.title}</h3>
                  <p className="text-xs font-medium text-slate-300 leading-relaxed">{item.desc}</p>
                  <div className="pt-2 flex items-center gap-1.5 text-[11px] font-extrabold text-[#00D66C]">
                    <ShieldCheck className="h-3.5 w-3.5" />
                    <span>100% Certified Clean</span>
                  </div>
                </div>

                {/* Hover Glow */}
                <div className="absolute inset-0 rounded-3xl border border-transparent group-hover:border-[#00D66C]/50 transition-colors pointer-events-none" />
              </motion.div>
            )
          })}
        </div>

      </div>

      
    </section>
  )
}
