import { motion } from 'framer-motion'
import {
  Leaf,
  Sun,
  BatteryCharging,
  Zap,
  ShieldCheck,
  ArrowRight,
  RefreshCw,
  Award,
  Download,
  CheckCircle2,
} from 'lucide-react'
import PageHero from '../components/sections/PageHero'

/* ── Energy Lifecycle Steps ── */
const lifecycleSteps = [
  {
    step: '01',
    title: 'Solar & Wind Generation',
    desc: '100% certified renewable electricity generated by station canopy solar panels and regional wind farms.',
    icon: Sun,
  },
  {
    step: '02',
    title: 'BESS Battery Storage',
    desc: 'Utility-scale on-site battery storage systems (BESS) balance grid power during peak demand hours.',
    icon: BatteryCharging,
  },
  {
    step: '03',
    title: '350kW Liquid Cooled Output',
    desc: 'Dispenses up to 400 miles of range per hour without thermal throttling or fossil-fuel grid strain.',
    icon: Zap,
  },
  {
    step: '04',
    title: 'Zero Tailpipe Emissions',
    desc: 'Replaces fossil fuels completely and eliminates urban carbon emissions across 40+ metro hubs.',
    icon: Leaf,
  },
]

/* ── Net-Zero Roadmap ── */
const roadmapMilestones = [
  { year: '2024', goal: '100% Solar-Backed Microgrids', status: 'Achieved' },
  { year: '2026', goal: '1,500+ Renewable Fast Charging Hubs', status: 'In Progress' },
  { year: '2028', goal: 'Second-Life Battery Repurposing Program', status: 'Upcoming' },
  { year: '2030', goal: 'Complete Net-Zero Scope 1, 2 & 3 Carbon Neutrality', status: 'Target' },
]

export default function SustainabilityPage() {
  return (
    <div className="w-full overflow-hidden bg-[#FAFCFA]">

      <PageHero
        badge="Green Mobility & Zero Emissions"
        badgeIcon={<Leaf className="h-3.5 w-3.5 fill-[#00D66C]" />}
        title="ZERO EMISSION DRIVING"
        titleHighlight="CLEAN GREEN FUTURE."
        description="Our chargers run on 100% certified renewable energy from solar canopies and wind farms with BESS grid stability."
        image="https://images.unsplash.com/photo-1509391365360-2e959784a276?auto=format&fit=crop&w=1400&q=80"
        imageAlt="Solar Canopy EV Charging Infrastructure"
      />

      {/* ─── SECTION 2: Environmental Impact Metrics Counter ─── */}
      <section className="py-20 sm:py-28 px-5 sm:px-8 max-w-7xl mx-auto space-y-16">
        <div className="text-center max-w-3xl mx-auto space-y-4">
          <span className="text-xs font-extrabold uppercase tracking-widest text-[#00D66C]">Verified Impact</span>
          <h2 className="text-[clamp(2rem,4.5vw,3.5rem)] font-black text-slate-900 tracking-tight leading-tight">
            Real Carbon <span className="text-[#00D66C]">Reduction.</span>
          </h2>
          <p className="text-slate-500 text-sm sm:text-base">
            Every megawatt-hour delivered by Indish-e-Volt replaces fossil fuels with 100% certified clean energy.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          <div className="rounded-3xl bg-white p-8 border border-slate-200 shadow-md space-y-3">
            <span className="text-xs font-extrabold uppercase tracking-widest text-slate-400">Total CO2 Avoided</span>
            <div className="text-4xl font-black text-[#00D66C]">128,450+ <span className="text-xs text-slate-500 font-bold">Tons</span></div>
            <p className="text-xs text-slate-500">Calculated across 8.4 million charging sessions nationwide.</p>
          </div>

          <div className="rounded-3xl bg-white p-8 border border-slate-200 shadow-md space-y-3">
            <span className="text-xs font-extrabold uppercase tracking-widest text-slate-400">Trees Equivalency</span>
            <div className="text-4xl font-black text-[#059669]">5.8 Million <span className="text-xs text-slate-500 font-bold">Trees</span></div>
            <p className="text-xs text-slate-500">Equal to planting a 25,000-acre mature forest.</p>
          </div>

          <div className="rounded-3xl bg-white p-8 border border-slate-200 shadow-md space-y-3">
            <span className="text-xs font-extrabold uppercase tracking-widest text-slate-400">Clean Energy Dispensed</span>
            <div className="text-4xl font-black text-slate-900">48.2 GWh <span className="text-xs text-slate-500 font-bold">Green Power</span></div>
            <p className="text-xs text-slate-500">100% verified solar and wind energy certificates (RECs).</p>
          </div>
        </div>
      </section>

      {/* ─── SECTION 3: 100% Solar Lifecycle Flow Diagram ─── */}
      <section className="py-20 bg-slate-950 text-white relative overflow-hidden">
        <div className="max-w-7xl mx-auto px-5 sm:px-8 space-y-16 relative z-10">
          <div className="text-center max-w-3xl mx-auto space-y-4">
            <span className="text-xs font-extrabold uppercase tracking-widest text-[#00D66C]">Clean Energy Architecture</span>
            <h2 className="text-3xl sm:text-5xl font-black tracking-tight">
              How Our Clean Energy <span className="text-[#00D66C]">Lifecycle Works.</span>
            </h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {lifecycleSteps.map((item) => {
              const Icon = item.icon
              return (
                <div
                  key={item.step}
                  className="rounded-3xl bg-slate-900/90 border border-slate-800 p-7 space-y-4 hover:border-[#00D66C] transition-all flex flex-col justify-between"
                >
                  <div className="space-y-4">
                    <div className="flex justify-between items-center">
                      <span className="text-2xl font-black text-[#00D66C]">{item.step}</span>
                      <div className="h-10 w-10 rounded-xl bg-[#E6F9EE] text-[#059669] flex items-center justify-center">
                        <Icon className="h-5 w-5" />
                      </div>
                    </div>
                    <h3 className="text-xl font-bold text-white">{item.title}</h3>
                    <p className="text-xs text-slate-400 leading-relaxed">{item.desc}</p>
                  </div>

                  <div className="pt-3 border-t border-slate-800 flex items-center gap-1.5 text-[11px] font-bold text-[#00D66C]">
                    <ShieldCheck className="h-3.5 w-3.5" /> 100% Certified Clean
                  </div>
                </div>
              )
            })}
          </div>
        </div>
      </section>

      {/* ─── SECTION 4: Circular Battery & Second Life BESS ─── */}
      <section className="py-20 sm:py-28 px-5 sm:px-8 max-w-7xl mx-auto space-y-16">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 lg:gap-16 items-center">
          <div className="space-y-6">
            <span className="text-xs font-extrabold uppercase tracking-widest text-[#00D66C]">Circular Economy</span>
            <h2 className="text-3xl sm:text-5xl font-black text-slate-900 tracking-tight leading-tight">
              Second-Life EV Battery <span className="text-[#00D66C]">Station Storage.</span>
            </h2>
            <p className="text-slate-500 text-sm sm:text-base leading-relaxed">
              We partner with automotive OEMs to repurpose retired EV traction batteries into station battery energy storage systems (BESS). Instead of entering landfills, retired batteries balance peak grid loads for another 10+ years.
            </p>

            <div className="space-y-3 pt-2">
              {[
                'Extends battery lifecycle by an additional 10 to 12 years',
                'Reduces station grid power demand spikes during peak hours',
                '98% material recycling rate upon ultimate end-of-life',
              ].map((item) => (
                <div key={item} className="flex items-center gap-3 text-sm font-bold text-slate-700">
                  <CheckCircle2 className="h-5 w-5 text-[#00D66C] shrink-0" />
                  <span>{item}</span>
                </div>
              ))}
            </div>
          </div>

          <div className="rounded-3xl overflow-hidden shadow-2xl border border-slate-200 aspect-[4/3]">
            <img
              src="https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=900&q=80"
              alt="BESS Battery Storage Station"
              className="w-full h-full object-cover"
            />
          </div>
        </div>
      </section>

      {/* ─── SECTION 5: Roadmap 2030 & ESG Report Banner ─── */}
      <section className="py-20 px-5 sm:px-8 max-w-7xl mx-auto">
        <div className="rounded-3xl bg-slate-950 text-white p-8 sm:p-14 border border-slate-800 shadow-2xl flex flex-col lg:flex-row items-center justify-between gap-8">
          <div className="space-y-4 max-w-2xl text-center lg:text-left">
            <span className="text-xs font-extrabold uppercase tracking-widest text-[#00D66C]">ESG Report 2026</span>
            <h2 className="text-3xl sm:text-5xl font-black tracking-tight leading-tight">
              Download Our Annual <span className="text-[#00D66C]">Sustainability Audit.</span>
            </h2>
            <p className="text-slate-300 text-sm sm:text-base leading-relaxed">
              Explore our net-zero carbon roadmap, microgrid deployment metrics, and environmental compliance audits certified by third-party auditors.
            </p>
          </div>

          <button
            onClick={() => alert('Downloading Indish-e-Volt ESG Annual Report 2026...')}
            className="flex items-center justify-center gap-2.5 px-8 py-4 rounded-full bg-[#00D66C] text-slate-950 font-black text-sm hover:bg-[#00C060] transition-all shrink-0 shadow-lg shadow-[#00D66C]/20"
          >
            <Download className="h-4 w-4" />
            <span>Download Full ESG Report (PDF)</span>
          </button>
        </div>
      </section>

    </div>
  )
}
